name: Deploy to Live Channel with GUI(Prod)

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'The Release version for deployment to Live Channel'
        type: string
        required: true

jobs:
  mamual-deploy-prod:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: "access_token"
          workload_identity_provider: 'projects/370510691583/locations/global/workloadIdentityPools/github-actions/subject/SUBJECT_ATTRIBUTE_VALUE'
          service_account: "github-action-582316782@modern-bond-394602.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: Download Artifact from GCS
        shell: bash
        # working-directory: "./wealsoft_techblog"
        run: |
          gsutil -m cp -r gs://wealsoft-techblog-test1/prod/dist-${{ inputs.releaseVersion }}.tar.gz ./
      - name: Unzip Artifact from GCS
        shell: bash
        # working-directory: "./wealsoft_techblog"
        run: |
          tar -zxvf dist-${{ inputs.releaseVersion }}.tar.gz
          ls -la
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MODERN_BOND_394602 }}'
          projectId: modern-bond-394602
          entryPoint: "wealsoft_techblog"
          channelId: live